### ISSUE TITLE
Doesn't work when same patch is fed as inputs.

### ISSUE THREAD

**Issue by naik-amey** [letatanu/DeepHomography#3]
If I feed the same patch (without any perturbation); 
The target will be [[0,0],[0,0],[0,0],[0,0]] in H_4point format or 3x3 identity matrix in H_matrix form. But the output from the model is pretty random. It doesn't work in this case. 
Any thoughts on why this is the case?

It also doesn't work in the case of simple translation in the x-direction.
The target will be [[16,0],[16,0],[16,0],[16,0]] in H_4point format.

**Comment by letatanu** [comment]
> If I feed the same patch (without any perturbation);
> The target will be [[0,0],[0,0],[0,0],[0,0]] in H_4point format or 3x3 identity matrix in H_matrix form. But the output from the model is pretty random. It doesn't work in this case.
> Any thoughts on why this is the case?
> 
> It also doesn't work in the case of simple translation in the x-direction.
> The target will be [[16,0],[16,0],[16,0],[16,0]] in H_4point format.

Sorry for the late reply. 
Hmmm... I haven't tested those cases. However, I thought because when I trained the network, random perturbation didn't produce those cases. Thus, the network cannot predict the homography well. I recommend you refine the network with those special cases based on the pre-trained network. I think it will handle them well.  

PS: Thank you for figuring it out. I might re-train the network when I have time to handle cases without perturbation.
